### ISSUE TITLE
Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by estebandiazm** [w9jds/firebase-action#45]
Hi,
The YML was working fine until 15/06/2020, now, the deployment is executed and I have this error:

![image](https://user-images.githubusercontent.com/7043052/85096161-240b2e00-b1b9-11ea-8608-efa16f8fd9a7.png)

I don't have many information from the github action log, I executed the command `firebase deploy` manually and it's working fine. This is my YML:

```
name: deploy

on:
  push:
    branches: [ master ]

jobs:

  deploy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
       node-version: [12.x]


    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Build App
      run: npm run build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

This is my firebase.json

```
{
  "hosting": {
    "public": "dist",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  }
}

```

Thanks for your help.

**Comment by jdbence** [comment]
I have a similar build script with this error in the log
```
2020-06-21T15:15:23.4140625Z > storage-engine@3.0.7 postinstall /usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine
2020-06-21T15:15:23.4140802Z > node ./compatibility/detect.js
2020-06-21T15:15:23.4140897Z 
2020-06-21T15:15:23.4904794Z [91mfs.js:114
2020-06-21T15:15:23.4905212Z     throw err;
2020-06-21T15:15:23.4905340Z     ^
2020-06-21T15:15:23.4905421Z 
2020-06-21T15:15:23.4905715Z Error: EACCES: permission denied, open '/usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine/lib/compatibility/index.js'
2020-06-21T15:15:23.4905921Z     at Object.openSync (fs.js:443:3)
2020-06-21T15:15:23.4906058Z     at Object.writeFileSync (fs.js:1194:35)
2020-06-21T15:15:23.4906213Z     at /usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine/lib/compatibility/detect.js:35:15
2020-06-21T15:15:23.4906393Z     at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine/lib/compatibility/detect.js:45:3)
2020-06-21T15:15:23.4906555Z     at Module._compile (internal/modules/cjs/loader.js:778:30)
2020-06-21T15:15:23.4906786Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-06-21T15:15:23.4906953Z     at Module.load (internal/modules/cjs/loader.js:653:32)
2020-06-21T15:15:23.4907095Z     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-06-21T15:15:23.4907237Z     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-06-21T15:15:23.4907385Z     at Module.require (internal/modules/cjs/loader.js:692:17)
2020-06-21T15:15:24.0976026Z [0m[91mnpm WARN optional[0m[91m SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/firebase-tools/node_modules/chokidar/node_modules/fsevents):
2020-06-21T15:15:24.0976281Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2020-06-21T15:15:24.0976450Z [0m[91m
2020-06-21T15:15:24.1879562Z [0m[91mnpm ERR! code[0m[91m ELIFECYCLE
2020-06-21T15:15:24.1888493Z [0m[91mnpm ERR! errno 1
2020-06-21T15:15:24.1888757Z npm ERR! storage-engine@3.0.7 postinstall: `node ./compatibility/detect.js`
2020-06-21T15:15:24.1889322Z npm ERR! Exit status 1
2020-06-21T15:15:24.1889497Z [0m[91mnpm ERR! 
2020-06-21T15:15:24.1889680Z npm ERR! Failed at the storage-engine@3.0.7 postinstall script.
2020-06-21T15:15:24.1889895Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-06-21T15:15:24.2284917Z [0m[91m
2020-06-21T15:15:24.2285097Z npm ERR! A complete log of this run can be found in:
2020-06-21T15:15:24.2285256Z npm ERR!     /root/.npm/_logs/2020-06-21T15_15_24_203Z-debug.log
2020-06-21T15:15:25.6193563Z The command '/bin/sh -c npm install -g firebase-tools' returned a non-zero code: 1
2020-06-21T15:15:25.6203591Z [0m
2020-06-21T15:15:25.6218567Z ##[warning]Docker build failed with exit code 1, back off 8.481 seconds before retry.
```

**Comment by w9jds** [comment]
This isn't really an issue with this action. I believe this is an issue related to how you have your action setup and how GitHub has changed the runners. Like I mention in the README it's highly recommended to use different steps to do different things in your build pipeline to make sure that your steps have clean environments. The way you have it basically tried to do everything in a single container.

**Comment by estebandiazm** [comment]
@w9jds I'm trying with your configuration example, I did it in differentes Jobs but I have the same return.

```
name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```
```
2020-06-22T20:16:43.4888794Z Artifact download has finished successfully
2020-06-22T20:16:43.4968528Z ##[group]Run w9jds/firebase-action@master
2020-06-22T20:16:43.4968726Z with:
2020-06-22T20:16:43.4968868Z   args: deploy --only hosting
2020-06-22T20:16:43.4968997Z env:
2020-06-22T20:16:43.4969556Z   FIREBASE_TOKEN: ***
2020-06-22T20:16:43.4969686Z ##[endgroup]
2020-06-22T20:16:43.4998960Z ##[command]/usr/bin/docker run --name c27d319d821c6bda76495a96c1ee85c94ac2ad_b6cf01 --label c27d31 --workdir /github/workspace --rm -e FIREBASE_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_API_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/curiscofitcoach-ui/curiscofitcoach-ui":"/github/workspace" c27d31:9d821c6bda76495a96c1ee85c94ac2ad deploy --only hosting
2020-06-22T20:16:45.8644644Z 
2020-06-22T20:16:45.8646102Z [1m[31mError:[39m[22m An unexpected error has occurred.
2020-06-22T20:16:46.3105549Z Post job cleanup.
2020-06-22T20:16:46.4085114Z [command]/usr/bin/git version
2020-06-22T20:16:46.4163118Z git version 2.27.0
2020-06-22T20:16:46.4200116Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-06-22T20:16:46.4245931Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2020-06-22T20:16:46.4491511Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-06-22T20:16:46.4523143Z http.https://github.com/.extraheader
2020-06-22T20:16:46.4534526Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2020-06-22T20:16:46.4569759Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2020-06-22T20:16:46.4838575Z Cleaning up orphan processes
```

**Comment by w9jds** [comment]
I can't actually reproduce this. I've run it both locally and through my own personal Github Action using the exact example and it is working as expected. Is there any other information you can give, and you deploy it locally without the action fine?

**Comment by estebandiazm** [comment]
> I can't actually reproduce this. I've run it both locally and through my own personal Github Action using the exact example and it is working as expected. Is there any other information you can give, and you deploy it locally without the action fine?

@w9jds How can I extact more information from GitHub Actions?, locally work fine using `firebase deploy --only hosting`
