### ISSUE TITLE
EACCESS with `npm install -g firebase-tools`

### ISSUE THREAD

**Issue by anandchakru** [w9jds/firebase-action#46]
```
2020-06-21T09:58:11.0318028Z Step 10/14 : RUN npm install -g firebase-tools
2020-06-21T09:58:11.0421728Z  ---> Running in 50ade17f217f
2020-06-21T09:58:12.9119224Z [91mnpm[0m[91m WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-06-21T09:58:26.9619471Z [0m/usr/local/bin/firebase -> /usr/local/lib/node_modules/firebase-tools/lib/bin/firebase.js
2020-06-21T09:58:27.0361948Z 
2020-06-21T09:58:27.0362975Z > protobufjs@6.9.0 postinstall /usr/local/lib/node_modules/firebase-tools/node_modules/protobufjs
2020-06-21T09:58:27.0363184Z > node scripts/postinstall
2020-06-21T09:58:27.0363272Z 
2020-06-21T09:58:27.2149187Z 
2020-06-21T09:58:27.2149704Z > storage-engine@3.0.7 postinstall /usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine
2020-06-21T09:58:27.2149889Z > node ./compatibility/detect.js
2020-06-21T09:58:27.2149986Z 
2020-06-21T09:58:27.2864720Z [91mfs.js:114
2020-06-21T09:58:27.2865857Z     throw err;
2020-06-21T09:58:27.2866847Z     ^
2020-06-21T09:58:27.2866917Z 
2020-06-21T09:58:27.2867087Z Error: EACCES: permission denied, open '/usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine/lib/compatibility/index.js'
2020-06-21T09:58:27.2867267Z     at Object.openSync (fs.js:443:3)
2020-06-21T09:58:27.2867416Z     at Object.writeFileSync (fs.js:1194:35)
2020-06-21T09:58:27.2867579Z     at /usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine/lib/compatibility/detect.js:35:15
2020-06-21T09:58:27.2867782Z     at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/storage-engine/lib/compatibility/detect.js:45:3)
2020-06-21T09:58:27.2867958Z     at Module._compile (internal/modules/cjs/loader.js:778:30)
2020-06-21T09:58:27.2868152Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-06-21T09:58:27.2868314Z     at Module.load (internal/modules/cjs/loader.js:653:32)
2020-06-21T09:58:27.2868465Z     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-06-21T09:58:27.2868618Z     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2020-06-21T09:58:27.2868773Z     at Module.require (internal/modules/cjs/loader.js:692:17)
2020-06-21T09:58:28.1712904Z [0m[91mnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/firebase-tools/node_modules/chokidar/node_modules/fsevents):
2020-06-21T09:58:28.1714351Z npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2020-06-21T09:58:28.1714837Z [0m[91m
2020-06-21T09:58:28.1715436Z [0m[91mnpm ERR! code[0m[91m ELIFECYCLE
2020-06-21T09:58:28.1716647Z [0m[91mnpm ERR! errno 1
2020-06-21T09:58:28.1717248Z [0m[91mnpm ERR![0m[91m storage-engine@3.0.7 postinstall: `node ./compatibility/detect.js`
2020-06-21T09:58:28.1717626Z npm ERR! Exit status 1
2020-06-21T09:58:28.1717925Z [0m[91mnpm ERR![0m[91m 
2020-06-21T09:58:28.1718244Z npm ERR! Failed at the storage-engine@3.0.7 postinstall script.
2020-06-21T09:58:28.1718608Z npm ERR![0m[91m This is probably not a problem with npm. There is likely additional logging output above.
2020-06-21T09:58:28.1718939Z [0m[91m
2020-06-21T09:58:28.1719250Z [0m[91mnpm ERR![0m[91m A complete log of this run can be found in:
2020-06-21T09:58:28.1719598Z npm ERR!     /root/.npm/_logs/2020-06-21T09_58_27_941Z-debug.log
2020-06-21T09:58:28.7264460Z The command '/bin/sh -c npm install -g firebase-tools' returned a non-zero code: 1
2020-06-21T09:58:28.7264706Z [0m
2020-06-21T09:58:28.7281969Z ##[warning]Docker build failed with exit code 1, back off 1.208 seconds before retry.
2020-06-21T09:58:29.9374851Z ##[command]/usr/bin/docker build -t 3888d3:c8ac01ba3f3548cdabe384e4965f3ee8 -f "/home/runner/work/_actions/w9jds/firebase-action/master/Dockerfile" "/home/runner/work/_actions/w9jds/firebase-action/master"
2020-06-21T09:58:29.9747718Z Sending build context to Docker daemon  10.75kB```

**Comment by ahmadalibaloch** [comment]
Getting the same problem. Started occurring minutes before. I think Node version needs to be updated?
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by anandchakru** [comment]
looks like an issue on the docker container's access. Reported it to [gh-community](https://github.community/t/eaccess-with-npm-install-g-firebase-tools/119079 as well

**Comment by ortoniKC** [comment]
The same problem, used sudo npm install, but still, I have the same issue, any solution?

**Comment by RianWardana** [comment]
I just encountered the same problem. I hope we can find the solution

**Comment by kenmueller** [comment]
Can't deploy as of now. This was working yesterday.

**Comment by sirrapa** [comment]
Same problem here. Is there a known workarround untill this is fixed?

**Comment by sebiweise** [comment]
Unfortunately, nothing works here either. Anyone got any ideas?

**Comment by hedleysmith** [comment]
Also having this issue - can't deploy anything. This issue could be related? https://github.com/firebase/firebase-tools/issues/2383

**Comment by aravindvnair99** [comment]
Facing the same issue all of a sudden. Unable to deploy anything.

**Comment by phoEnix-511** [comment]
+1
All builds have failed all of a sudden. Is there any workaround for now?

**Comment by ridhianand16** [comment]
Try replacing the command
```
RUN npm install -g firebase-tools
```

with 
```
RUN curl -sL https://firebase.tools | bash
```

**Comment by w9jds** [comment]
Looking into this now, it seems to be a `firebase-tools` issue, but I think I might be able to push a new version to work around it with an upgraded LTS base image.

**Comment by GiladShoham** [comment]
try using the --unsafe-perm flag or configure an env variable: 
NPM_CONFIG_USER root before the install

**Comment by w9jds** [comment]
v1.4.0 has been released. If you are using `@master` re-running it should now be fixed. If you are pointing to a specific version, update it to the latest release.

**Comment by aravindvnair99** [comment]
> v1.4.0 has been released. If you are using `@master` re-running it should fix it. If you are pointing to a specific version, update it to the latest release.

Thanks a lot for the quick update @w9jds ! Unfortunately `@master` didn't work, but setting it explicitly to `v1.4.0` did the job.

**Comment by ivanbeldad** [comment]
@aravindvnair99 It worked for me.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 It worked for me using `master`.

@ivanbeldad Thanks for informing! I tried `master` again and can confirm it works!

**Comment by sebiweise** [comment]
Now it worked Nahct today, since a few minutes ago unfortunately not anymore.

**Comment by phoEnix-511** [comment]
Step 11/15 : RUN npm install -g firebase-tools
 ---> Running in 57079ef36d4c
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/firebase-tools/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/DABH/diagnostics.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-22T06_39_17_772Z-debug.log
The command '/bin/sh -c npm install -g firebase-tools' returned a non-zero code: 254



The previous issue is fixed but unfortunately, now there's another issue.

**Comment by ronaldohoch** [comment]
Same here!

` Run w9jds/firebase-action@master2s
    FIREBASE_TOKEN: ***
Run w9jds/firebase-action@master
  with:
    args: deploy --only hosting
  env:
    FIREBASE_TOKEN: ***
/usr/bin/docker run --name e5ae59678a1483080a4da8b34a48925d606eba_965aaa --label e5ae59 --workdir /github/workspace --rm -e FIREBASE_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/agencie-precifique/agencie-precifique":"/github/workspace" e5ae59:678a1483080a4da8b34a48925d606eba deploy --only hosting

Error: An unexpected error has occurred.`
