### ISSUE TITLE
Broke deployment

### ISSUE THREAD

**Issue by amitava82** [w9jds/firebase-action#49]
Just started getting error. Everything was going well couple of hours back.
```
Error: 'linux-x64' binaries cannot be used on the 'linuxmusl-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.
```

**Comment by milo-** [comment]
As a workaround, I've moved `npm install` to the firebase functions predeploy step

**Comment by amitava82** [comment]
Thanks! I've removed sharp and using Jimp for now. Is this due to recent changes in firebase-tools?

**Comment by Banakin** [comment]
Ive gotten a similar issue

This is what I get when trying to use canvas in my cloud function.
```
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /github/workspace/functions/node_modules/canvas/build/Release/libpixman-1.so.0)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/github/workspace/functions/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
```

With some research I've found that it seems to have to do with an Alpine NodeJS Docker image.

**Comment by Banakin** [comment]
Update:
I looked at the code of this repo and yes there is an Alpine Docker image. I tried a few things but what worked best was using the NodeJS Docker image that uses Debian Buster instead of Alpine Linux.

I forked and changed this over at [my repo](https://github.com/Banakin/firebase-action).

Let me know if it works for you guys, I could make a pull request if people are interested. Im new to helping with issues so i dont know the proper etiquette.

**Comment by w9jds** [comment]
You could have just rolled back the deployed version too. Going back like 2 version would have moved you back to a different node image.

**Comment by Banakin** [comment]
Oh I didn't realize that. I tried 1.4.0 and it didnt work but 1.3.1 seemed to do the trick. Thanks!

**Comment by bartekpacia** [comment]
I also encountered this today with `sharp` package. Adding `npm ci --arch=x64 --platform=linuxmusl` fixed this for me.
