### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by aravindvnair99** [w9jds/firebase-action#98]
Hey @w9jds!

I was trying to deploy using the GitHub Actions but ended up with an error: https://github.com/aravindvnair99/Spot-the-Hole/runs/3006448241?check_suite_focus=true

```console
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /github/workspace/functions/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/github/workspace/functions/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
```

Was wondering if you had any insights. Is it because of alpine?

https://github.com/w9jds/firebase-action/blob/a17f996b089638653d57c7aa85d0763e256b13fb/Dockerfile#L1

**Comment by w9jds** [comment]
Yeah it looks like `libc6-compat` is missing from the alpine images.

**Comment by aravindvnair99** [comment]
> Yeah it looks like `libc6-compat` is missing from the alpine images.

Thank you for your quick response @w9jds. I just came across this:

> The main caveat to note is that it does use musl libc instead of glibc and friends, so software will often run into issues depending on the depth of their libc requirements/assumptions.

mentioned at https://hub.docker.com/_/node
